### ISSUE TITLE
flask_limiter fails with AttributeError: 'NoneType' object has no attribute 'hit' with flask_restful Resource

### ISSUE THREAD

**Issue by flound1129** [alisaifee/flask-limiter#150]
app.py: 
```
from flask import Flask
from flask_restful import Resource, Api
from hello import Hello
 
app = Flask(__name__)
api = Api(app)
 
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
 
limiter = Limiter(
    app,
    key_func=get_remote_address,
    default_limits=["200 per day", "50 per hour"],
    storage_uri='redis://localhost:6379'
 )
 
api.add_resource(Hello, '/')
 
if __name__ == '__main__':
    app.run(debug=True)
```

endpoint.py:

```from flask import Flask, current_app
from flask_restful import Resource, Api
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
 
limiter = Limiter(
    current_app,
    key_func=get_remote_address,
    default_limits=["200 per day", "50 per hour"],
    storage_uri='redis://localhost:6379'
 
)
 
class Endpoint(Resource):
    decorators = [limiter.limit('6 per minute')]
```

hello.py

```from flask import Flask, current_app
from flask_restful import Resource, Api
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from endpoint import Endpoint
 
class Hello(Endpoint):
    def get(self):
        return {'hello': 'world'}
```

When trying to connect to '/' the following exception occurs:

```Traceback (most recent call last):
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return self.handle_error(e)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_limiter/extension.py", line 542, in __inner
    self.__check_request_limit(False)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_limiter/extension.py", line 479, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/amckenna/PycharmProjects/flask-bug/venv/lib/python2.7/site-packages/flask_limiter/extension.py", line 336, in __evaluate_limits
    if not self.limiter.hit(lim.limit, *args):
AttributeError: 'NoneType' object has no attribute 'hit'
127.0.0.1 - - [14/Jun/2018 13:37:48] "GET /?__debugger__=y
```

**Comment by vulcan25** [comment]
I am also seeing this error, when trying to initialize Limiter within a pluggable view using `current_app` instead of `app`, and applying the decorators to a `Flask.views.MethodView` class.

My `extension.py`:

```
from flask import current_app, _app_ctx_stack
from flask.views import MethodView

from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

limiter = Limiter(current_app, key_func=get_remote_address,default_limits=['100 per day'])

class Statistics(MethodView):
    decorators = [limiter.limit("10/second")]

    def dispatch_request(self):
        return 'I am a statistics view.'
```
And my application factory:

	from flask import Flask, Blueprint
	from extension import Statistics


	def create_app(config_filename):
		app = Flask(__name__)
		app.config.from_pyfile('the-config.cfg')

		the_api = Blueprint('the_api', __name__)	
		the_api.add_url_rule('/bananas', view_func=Statistics.as_view('the_api'))
		app.register_blueprint(the_api)

		return app

Traceback:



```
Traceback (most recent call last):
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask_limiter/extension.py", line 542, in __inner
    self.__check_request_limit(False)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask_limiter/extension.py", line 479, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/Users/kevin/src/venv/lib/python3.7/site-packages/flask_limiter/extension.py", line 336, in __evaluate_limits
    if not self.limiter.hit(lim.limit, *args):
AttributeError: 'NoneType' object has no attribute 'hit'
```

**Comment by gbabic** [comment]
I'm getting the same error with my setup. 

blueprints.py (obfuscated slightly):

```
from flask import Response
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from api.decorators import requires_auth
from flask import current_app as app


limiter = Limiter(app, key_func=get_remote_address)
endpoint_limit = limiter.shared_limit("100/hour", scope='endpoint')

@my_app.route('/endpoint', methods=['POST'])
@requires_auth
@endpoint_limit
def endpoint():
    ...
```

Traceback (most recent call last):
```
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/api/decorators.py", line 14, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 542, in __inner
    self.__check_request_limit(False)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 479, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 462, in __check_request_limit
    self.__evaluate_limits(endpoint, all_limits)
  File "/usr/local/lib/python3.7/site-packages/flask_limiter/extension.py", line 336, in __evaluate_limits
    if not self.limiter.hit(lim.limit, *args):
AttributeError: 'NoneType' object has no attribute 'hit'
```

Same error even with a more bare-bones setup. Anyone get anywhere with this?

**Comment by gbabic** [comment]
I have found the issue. It was indeed my fault and it boiled down to how I initialized my flask app and it's extensions.

Inside my api/blueprints.py I now have
```
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

my_api = Blueprint('my_api', __name__)
limiter = Limiter(key_func=get_remote_address)
my_limit = limiter.limit('1 per second')

@my_api.route('/validate', methods=['GET'])
@validation_limit
def endpoint():
   ...
```
notice that I don't pass app to Limiter here but I do declare it.

Then in my factory.py (Where my create_app method lives):
```
from flask import Flask

def create_app(config=None):
    app = Flask(__name__)
    # your configuration should go here
    
    # initialize the db
    from api.models import db
    db.init_app(app)
    
    
    # initialize the limiter!
    from api.blueprints import limiter
    limiter.init_app(app)

    # register the api routes
    from api.blueprints import my_api
    app.register_blueprint(my_api)

    return app
```

the key here are the inline imports and the deferred initialization of the limiter.

I hope this helps someone who was lost like me. Let me know if it helps!

**Comment by amarjayr** [comment]
I was having this same issue with `flask restful`. Hopefully someone else finds this useful...

### Here was my setup:
`Python 3.7.3`, `Flask-Limiter 1.3.1`, `Flask 1.1.2`
`app.py`
```
from limiter_util import limiter

def create_app():
   limiter.init_app(app)
```

`limiter_util.py`
```
from flask_limiter import Limiter

limiter = Limiter(
    key_func=get_limiter_key
)
```

`resource.py`
```
from limiter_util import limiter

class ExResource(Resource):
  @limiter.limit('1/minute')
  def post(self):
```
This set up produced the same error as above. 

### What I found:
* Two different instances of `limiter` seem to exist. Not sure how this is possible because `limiter.__init__` is only called once...
  * `current_app.extensions['limiter'] != limiter` when it should
* When the `@limiter.limit('1/minute')`'s factory is called it does not use the application context limiter
* The application context limiter is the only one with access to the data store (`Redis` in my case)

I think this is happening because `@limiter.limit('1/minute')` is called before the Flask application context is pushed. 

### How I hacked/fixed it:
Made a local version of [extension.py](https://github.com/alisaifee/flask-limiter/blob/master/flask_limiter/extension.py) in my project. Modified [extension.py:494](https://github.com/alisaifee/flask-limiter/blob/master/flask_limiter/extension.py#L494) from `"%s.%s" % (view_func.__module__, view_func.__name__)` to `"%s.%s" % (view_func.__module__, 'rate_limit')`

In my `resource.py` I changed it to:
```
class ExResource(Resource):
  def post(self):
      limiter = current_app.extensions['limiter']

        @limiter.limit('1/day')
        def rate_limit():
            pass

        return rate_limit()
```
This ensures that we use the application context `limiter`. You may have to play around with your modules and the naming.

Hope this helps!

**Comment by alisaifee** [comment]
Closing due to inactivity
