### ISSUE TITLE
No module named 'limits.errors'; 'limits' is not a package

### ISSUE THREAD

**Issue by ElegantFx** [alisaifee/flask-limiter#260]
Just writing this line of code:
`from flask_limiter import Limiter`

I get the error:
`Traceback (most recent call last):
  File ".../app.py", line 8, in <module>
    from flask_limiter import Limiter
  File "...\Python\Python36\lib\site-packages\flask_limiter\__init__.py", line 4, in <module>
    from .extension import Limiter, HEADERS
  File "...\Python\Python36\lib\site-packages\flask_limiter\extension.py", line 14, in <module>
    from limits.errors import ConfigurationError
ModuleNotFoundError: No module named 'limits.errors'; 'limits' is not a package`
Although the limits package is installed and working.

**Comment by ElegantFx** [comment]
My bad, solved.

**Comment by driesmp** [comment]
What was the error?
-
