### ISSUE TITLE
Can not install flask limiter using Python 2.6

### ISSUE THREAD

**Issue by yeweidaniel** [alisaifee/flask-limiter#73]
I have already run `pip install flask-limiter` and `pip install werkzeug` but when executing my python code I get this error

> Traceback (most recent call last):
>   File "rw_container_api/routes/v1/pricing.py", line 3, in <module>
>     from flask_limiter import Limiter
>   File "/usr/lib/python2.6/site-packages/flask_limiter/__init__.py", line 8, in <module>
>     from .errors import ConfigurationError, RateLimitExceeded
>   File "/usr/lib/python2.6/site-packages/flask_limiter/errors.py", line 14, in <module>
>     _patch_werkzeug()
>   File "/usr/lib/python2.6/site-packages/flask_limiter/errors.py", line 9, in _patch_werkzeug
>     if pkg_resources.get_distribution("werkzeug").version < "0.9":
>   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 292, in get_distribution
>     if isinstance(dist,Requirement): dist = get_provider(dist)
>   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 176, in get_provider
>     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
>     raise DistributionNotFound(req)
> pkg_resources.DistributionNotFound: werkzeug

I am running python 2.6.  Is there a problem with this setup or theres something that I have missed?

**Comment by alisaifee** [comment]
@yeweidaniel were you able to resolve the installation issue? I haven't been able to reproduce this at all.

**Comment by alisaifee** [comment]
Closing due to inactivity.
