### ISSUE TITLE
raising exception when rate limit is exceeded crashes

### ISSUE THREAD

**Issue by havok2063** [alisaifee/flask-limiter#74]
I'm trying to implement the rate limiter for my flask routes and I want to test it out and see if it works properly once the rate limit has been exceeded.  When I issue a request on a route beyond the rate limit, I'm getting this crash.  Since ```six``` is being called, this looks like a Python 2 to 3 bug.  I'm using Python 2.7.  

I'm using a Class-based View routing system so I'm using the rate limiter like so, e.g.

```
class QueryView(BaseView):
    """Class describing API calls related to queries."""
    decorators = [limiter.limit("1/minute")]

    def index(self):
        output = {'status': 1}
        return jsonify(result=output)
```
When if run one of these routes more than once per minute, it should raise a 429 but crashes with the below error.  Is this a real bug or is this related to my class-based view?

```
Traceback (most recent call last):
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask_limiter/extension.py", line 427, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/Users/Brian/anaconda2/lib/python2.7/site-packages/flask_limiter/extension.py", line 395, in __check_request_limit
    , lim.limit, lim.key_func(), limit_scope
TypeError: warning() takes at most 3 arguments (5 given)
```

**Comment by havok2063** [comment]
The issue here is that the logging format is way out of date and needs to be updated to the modern mechanism of either 

`self.logger.warning("ratelimit %s (%s) exceeded at endpoint: %s" % (lim.limit, lim.key_func(), limit_scope))`
or 
`self.logger.warning("ratelimit {0} ({1}) exceeded at endpoint: {2}".format(lim.limit, lim.key_func(), limit_scope))`

**Comment by alisaifee** [comment]
Thanks @havok2063. I will address this issue this week (unless you have a PR you could push?)

**Comment by havok2063** [comment]
Hi.  Thanks @alisaifee .  The main issue was with a custom logger that I was using no longer accepted the old format of specifying multiple arguments, and was mainly written to accept either of the two formats in my previous post.  I fixed it in my code and got everything working with the original limiter code.  Since the fix was mostly on my end, I don't have a PR, but it might be a good idea to update that code just in case other people are using custom loggers that are only designed to accept a single string message.

**Comment by alisaifee** [comment]
@havok2063 could you please share an example of the custom logger you are using? Also, I'm having some difficulty finding documentation on the deprecation of emitting warnings via the `logging.warning(msg, *args, **kwargs)` signature
