### ISSUE TITLE
Python 3.5 Errors

### ISSUE THREAD

**Issue by EndenDragon** [alisaifee/flask-limiter#82]
Hello, after upgrading my codebase to use python3.5 (from python 2.7), Flask-limiter refuses to work, I am not sure what went wrong. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/local/lib/python3.5/dist-packages/flask_limiter/extension.py", line 434, in __check_request_limit
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask_limiter/extension.py", line 399, in __check_request_limit
    if not self.limiter.hit(lim.limit, *filter(None, [self._key_prefix, limit_key, limit_scope])):
  File "/usr/local/lib/python3.5/dist-packages/limits/strategies.py", line 124, in hit
    self.storage().incr(item.key_for(*identifiers), item.get_expiry())
  File "/usr/local/lib/python3.5/dist-packages/limits/limits.py", line 74, in key_for
    str(self.amount), str(self.multiples), self.granularity[1]
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by alisaifee** [comment]
Hi @EndenDragon. Looks like the error is caused either by the `key_prefix` or the actual rate limit key. Do you have the key prefix value (`RATELIMIT_KEY_PREFIX`) set in your configuration. If not, is your rate limit string static or dynamic?

**Comment by Rolinh** [comment]
Hi,
fwiw, I hit a very similar issue when I enable headers, either through the constructor or by setting `RATELIMIT_HEADERS_ENABLED` to true (using python 3.4. flask-limiter 0.9.5.1):

```
Traceback (most recent call last):
  File "/tmp/pyenv/lib/python3.4/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/tmp/pyenv/lib/python3.4/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask/app.py", line 1856, in process_response
    response = handler(response)
  File "/tmp/pyenv/lib/python3.4/site-packages/flask_limiter/extension.py", line 296, in __inject_headers
    window_stats = self.limiter.get_window_stats(*current_limit)
  File "/tmp/pyenv/lib/python3.4/site-packages/limits/strategies.py", line 149, in get_window_stats
    remaining = max(0, item.amount - self.storage().get(item.key_for(*identifiers)))
  File "/tmp/pyenv/lib/python3.4/site-packages/limits/limits.py", line 74, in key_for
    str(self.amount), str(self.multiples), self.granularity[1]
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Rolinh** [comment]
Forget about my comment, my custom `key_func` was returning `None` in some conditions instead of always a string (and then, `limit_key` being `None` generates the above error).

**Comment by EndenDragon** [comment]
@Manojaditya this is a different issue and unrelated to the flask limiter package. Usually a helpful message about the error can be found at the end of the error traceback. In that case I can see that it said `API_KEY not set`. You should probably set your API key.
